"""empty message

Revision ID: 35ea2b9b01fc
Revises: bee18ba3fc51
Create Date: 2022-01-29 07:16:43.491453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ea2b9b01fc'
down_revision = 'bee18ba3fc51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.drop_index('ix_kullanici_eposta', table_name='kullanici')
    op.drop_index('ix_kullanici_kullanici_adi', table_name='kullanici')
    op.drop_table('kullanici')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kullanici',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('kullanici_adi', sa.VARCHAR(length=64), nullable=True),
    sa.Column('eposta', sa.VARCHAR(length=120), nullable=True),
    sa.Column('sifre_hash', sa.VARCHAR(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_kullanici_kullanici_adi', 'kullanici', ['kullanici_adi'], unique=False)
    op.create_index('ix_kullanici_eposta', 'kullanici', ['eposta'], unique=False)
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
